In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://www.cdc.gov/ebola/situation-summary/index.html"

# In the case cdc changes the url, I would only need to update it here

In [3]:
response = requests.get(url)
response

In [4]:
response.text[:500]

'<!DOCTYPE html>\r\n<html lang="en-us" class="cdc-theme-cdc cdc-page-type--content" >\r\n<head>\r\n\t\r\n<meta charset="UTF-8" />\r\n<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\r\n<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" />\r\n<meta name="mobile-web-app-capable" content="yes" />\r\n<meta name="apple-mobile-web-app-capable" content="yes" />\r\n<link rel="apple-touch-icon" sizes="180x180" href="/TemplatePackage/5.0/img/favicon/apple-touch-icon.png">\r\n<link rel='

In [5]:
soup = BeautifulSoup(response.text, "html.parser")
soup

<!DOCTYPE html>

<html class="cdc-theme-cdc cdc-page-type--content" lang="en-us">
<head>
<meta charset="utf-8"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
<meta content="yes" name="mobile-web-app-capable"/>
<meta content="yes" name="apple-mobile-web-app-capable"/>
<link href="/TemplatePackage/5.0/img/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/TemplatePackage/5.0/img/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/TemplatePackage/5.0/img/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link color="#0056b3" href="/TemplatePackage/5.0/img/favicon/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#0056b3" name="msapplication-TileColor"/>
<meta content="#0056b3" name="theme-color"/>
<link href="/TemplatePackage/5.0/css/app.min.css?_=97046" rel="stylesheet prefetch"/>
<link href="/TemplatePackage/5.0/css/print.min.css?_=97046" media="print" rel="stylesheet"/>
<link href="/TemplatePackage/5.0/json/manifest.json" rel="manifest"/>
<script src="https://www.cdc.gov/JScript/dmat/cdc-dmat.min.js?account=cdcgov&amp;_=00713"></script>
<meta content="5.0" property="cdc:template_version"/>
<title>Ebola Outbreak: Current Situation | Ebola | CDC</title>
<meta content="Learn about the current outbreak of Ebola disease affecting DRC and Uganda." name="description"/>
<meta content="article" property="og:type"/>
<meta content="Ebola Outbreak: Current Situation" property="og:title"/>
<meta content="https://www.cdc.gov/ebola/situation-summary/index.html" property="og:url"/>
<meta content="Learn about the current outbreak of Ebola disease affecting DRC and Uganda." property="og:description"/>
<meta content="205691699516606" property="fb:app_id"/>
<meta content="Ebola" property="og:site_name"/>
<meta content="CDC" property="og:author"/>
<meta content="https://www.cdc.gov/ebola/media/images/2026/06/Ebola_map2.png?_=39780" property="og:image"/>
<meta content="image/png" property="og:image:type"/>
<meta content="2026-06-26T15:29:30-04:00" property="og:updated_time"/>
<meta content="CDC" property="article:author"/>
<meta content="summary" name="twitter:card"/>
<meta content="Ebola Outbreak: Current Situation" name="twitter:title"/>
<meta content="https://www.cdc.gov/ebola/situation-summary/index.html" name="twitter:url"/>
<meta content="Learn about the current outbreak of Ebola disease affecting DRC and Uganda." name="twitter:description"/>
<meta content="@CDCgov" name="twitter:site"/>
<meta content="@CDCgov" name="twitter:creator"/>
<meta content="https://www.cdc.gov/ebola/media/images/2026/06/Ebola_map2.png?_=39780" name="twitter:image:src"/>
<meta content="index, archive" name="robots"/>
<meta content="May 17, 2026" property="cdc:first_published"/>
<meta content="June 26, 2026" property="cdc:last_updated"/>
<meta content="June 26, 2026" property="cdc:last_reviewed"/>
<meta content="NATIONAL CENTER FOR EMERGING AND ZOONOTIC INFECTIOUS DISEASES" property="cdc:content_source"/>
<meta content="NATIONAL CENTER FOR EMERGING AND ZOONOTIC INFECTIOUS DISEASES" property="cdc:maintained_by"/>
<meta content="853" property="cdc:content_id"/>
<meta content="5837" property="cdc:build"/>
<meta content="4.26.6" property="cdc:version"/>
<meta content="cdc_dfe" property="cdc:page_type"/>
<meta content="dfe" property="cdc:page_origin"/>
<link href="https://www.cdc.gov/ebola/situation-summary/index.html" rel="canonical"/>
<meta content="4.26.6 - b.5837" property="cdc:wcms_build"/>
<meta content="2026-06-26T15:29:30Z" name="DC.date"/>
<meta content="2026-06-26T15:32:55Z" name="cdc:last_published"/>
<meta content="0.3" property="cdc:dfe_version"/>
<meta content="cdc_situation_summary" property="cdc:dfe_content_type"/>
<meta content="1.3.2" property="cdc:dfe_content_type_version"/>
</head>
<body class="no-js cdc-post-type--cdc-dfe cdc-dfe-cdc_situation_summary" data-audience="gen">
<div id="skipmenu">
<a class="usa-skipnav" href="#content">Skip directly to site content</a>
<a class="usa-skipnav" href="#cdc-search__input">Skip directly to search</a>
</div>
<div class="cdc-page-banner container noindex">
<div aria-label="Official website of the United States government" class="cdc-site-gov-notice noindex noprint">
<div class="cdc-page-offset">
<div class="cdc-site-gov-notice__header">
<div>
<img alt="" aria-hidden="true" class="usa-banner__header-flag" height="11" src="/TemplatePackage/5.0/img/uswds/us_flag_small.png" width="16"/>
<span>An official website of the United States government</span>
</div>
<span>
<a aria-controls="gov-notice" aria-expanded="false" data-bs-toggle="collapse" href="#gov-notice" role="button">
					Here's how you know
					<span aria-hidden="true" class="cdc-fa-angle-down"></span>
</a>
</span>
</div>
<div aria-hidden="true" class="collapse" id="gov-notice">
<div class="row">
<div class="col-12 col-lg-6">
<img alt="" aria-hidden="true" src="/TemplatePackage/5.0/img/uswds/icon-dot-gov.svg"/>
<div>
<b>Official websites use .gov</b>
<p>A <b>.gov</b> website belongs to an official government organization in the United States.</p>
</div>
</div>
<div class="col-12 col-lg-6">
<img alt="" aria-hidden="true" src="/TemplatePackage/5.0/img/uswds/icon-https.svg"/>
<div>
<strong>Secure .gov websites use HTTPS</strong>
<p>A <strong>lock</strong> ( <i aria-hidden="true" class="cdc-icon-lock-01"></i> ) or <strong>https://</strong> means you've safely connected to the .gov website. Share sensitive information only on official, secure websites.</p>
</div>
</div>
</div>
</div>
</div>
</div>
<div data-cdc-site-alert=""></div>
<script src="/TemplatePackage/5.0/js/modules/banner.js"></script>
</div>
<header class="container cdc-header noindex" role="banner">
<script>document.body.dataset.audience = 'gen';</script>
<div class="cdc-header__desktop">
<div class="cdc-page-offset">
<div class="cdc-header__cdc-logo">
<a href="https://www.cdc.gov">
<img alt="Centers for Disease Control and Prevention. CDC twenty four seven. Saving Lives, Protecting People" src="/TemplatePackage/5.0/img/logo/logo-notext.svg"/>
</a>
</div>
<div class="cdc-header__body">
<div class="cdc-header__title">
<a class="cdc-header__title-link" href="/ebola/index.html">
						Ebola					</a>
</div>
<div class="cdc-header__components">
<!-- Must Have At Least 3 Pages in Audience or Multiple Audience -->
<div class="cdc-header__menu">
<button class="btn btn-outline-white btn-arrow-down btn-fancy" id="megaButton">
						Explore This Topic					</button>
</div>
<form action="https://search.cdc.gov/search/" class="cdc-header__search" method="GET" role="search">
<button aria-controls="cdc-header__search-inner" id="cdc-search__toggle" type="button">Search</button>
<div aria-labelledby="cdc-search__toggle" class="input-group cdc-header__search__group" id="cdc-header__search-inner">
<label class="visually-hidden" for="cdc-search__input">Search</label>
<input autocomplete="off" class="form-control" data-search-input="" id="cdc-search__input" maxlength="300" name="query" placeholder="Search" type="search"/>
<button class="cdc-header__search-clear btn" id="cdc-search__clear" type="button">
<span aria-hidden="true" class="cdc-header__search-icon cdc-fa-xmark"></span>
<span class="visually-hidden">Clear</span>
</button>
<button class="cdc-header__search-submit btn" id="cdc-search__submit" type="submit">
<span aria-hidden="true" class="cdc-header__search-icon cdc-fa-magnifying-glass"></span>
<span class="visually-hidden">Search</span>
</button>
</div>
</form>
</div>
</div>
</div>
</div>
<div class="cdc-megamenu" role="navigation">
<div class="cdc-megamenu__cols cdc-page-offset" role="menu">
<div class="cdc-megamenu__col" data-audience="gen">
<div class="cdc-megamenu__heading">
<a href="/ebola/index.html" role="menuitem">
<span>For Everyone</span>
<span class="cdc-fa-regular cdc-fa-house"></span>
</a>
</div>
<div class="cdc-megamenu__links">
<ul class="list-unstyled" role="menu">
<li role="menuitem">
<a class="truncate" data-post-id="853" href="/ebola/situation-summary/index.html">
								Current Situation							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="43" href="/ebola/about/index.html">
								About							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="53" href="/ebola/signs-symptoms/index.html">
								Signs and Symptoms							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="71" href="/ebola/outbreaks/index.html">
								Outbreak History							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="54" href="/ebola/causes/index.html">
								How It Spreads							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="854" href="/ebola/faq/index.html">
								FAQs							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="76" href="/ebola/hcp/communication-resources/index.html">
								Ebola Communication Resources							</a>
</li>
<li role="menuitem">
<a class="cdc-megamenu-all" href="/ebola/site.html#gen">
								View all							</a>
</li>
</ul>
</div>
</div>
<div class="cdc-megamenu__col" data-audience="hcp">
<div class="cdc-megamenu__heading">
<a href="/ebola/hcp/index.html" role="menuitem">
<span>Health Care Providers</span>
<span class="cdc-fa-regular cdc-fa-house"></span>
</a>
</div>
<div class="cdc-megamenu__links">
<ul class="list-unstyled" role="menu">
<li role="menuitem">
<a class="truncate" data-post-id="73" href="/ebola/hcp/clinical-guidance/index.html">
								Clinical Guidance							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="47" href="/ebola/hcp/clinical-signs/index.html">
								Clinical Features							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="184" href="/ebola/hcp/vaccines/index.html">
								Vaccine Product Information							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="75" href="/ebola/hcp/training/index.html">
								Training							</a>
</li>
<li role="menuitem">
<a class="cdc-megamenu-all" href="/ebola/site.html#hcp">
								View all							</a>
</li>
</ul>
</div>
</div>
<div class="cdc-megamenu__col" data-audience="php">
<div class="cdc-megamenu__heading">
<a href="/ebola/php/index.html" role="menuitem">
<span>Public Health</span>
<span class="cdc-fa-regular cdc-fa-house"></span>
</a>
</div>
<div class="cdc-megamenu__links">
<ul class="list-unstyled" role="menu">
<li role="menuitem">
<a class="truncate" data-post-id="878" href="/ebola/php/emergency-guidance/index.html">
								Interim Public Health Travel Guidance							</a>
</li>
<li role="menuitem">
<a class="truncate" data-post-id="816" href="/ebola/php/public-health-strategy/index.html">
								Public Health Strategy							</a>
</li>
<li role="menuitem">
<a class="cdc-megamenu-all" href="/ebola/site.html#php">
								View all							</a>
</li>
</ul>
</div>
</div>
</div>
<div class="cdc-megamenu__footer">
<div class="col cdc-page-offset">
<div class="cdc-megamenu-footer-item cdc-megamenu-footer-item--left">
<div class="cdc-megamenu-related">
<p class="cdc-megamenu__footer-title">
<strong>
							Related Topics:
						</strong>
</p>
<div class="cdc-megamenu__linklist">
<a data-post-id="" href="/viral-hemorrhagic-fevers/about/index.html">
								About Viral Hemorrhagic Fevers							</a>
</div>
</div>
</div>
<div class="cdc-megamenu-footer-item cdc-megamenu-footer-item--right">
<a class="btn btn-outline-blue site-index-link" href="/ebola/index.html">
						Home					</a>
</div>
</div>
</div>
</div>
<div class="cdc-header-mobile dropdown">
<div class="cdc-header-mobile__top">
<a href="https://www.cdc.gov">
<img alt="Centers for Disease Control and Prevention. CDC twenty four seven. Saving Lives, Protecting People" class="cdc-logo-mobile" src="/TemplatePackage/5.0/img/logo/logo-notext.svg"/>
</a>
<div class="cdc-header-mobile__buttons">
<a aria-controls="mobile-search-body" class="search-link" href="#" id="mobile-search-toggle">
<i class="cdc-fa-regular cdc-fa-magnifying-glass"><span class="visually-hidden">search</span></i>
</a>
<div aria-labelledby="mobile-search-toggle" class="cdc-mobile-menu-search" id="mobile-search-body">
<form action="https://search.cdc.gov/search/" aria-labelledby="cdc-mobile-search-toggle" class="cdc-mobile-search" id="cdc-mobile-search-body" method="GET" role="search">
<div class="input-group">
<input class="form-control cdc-mobile-search__input" data-search-input="" maxlength="300" name="query" placeholder="Search" required="" tabindex="-1" type="search"/>
<button class="btn btn-outline-secondary btn--clear" type="button"><span aria-hidden="true" class="cdc-fa-light cdc-fa-xmark"></span><span class="visually-hidden">clear</span></button>
<button class="btn btn-outline-secondary btn--search" type="submit"><i class="cdc-fa-light cdc-fa-magnifying-glass"></i><span class="visually-hidden">search</span></button>
</div>
</form>
</div>
</div>
</div>
<div aria-level="1" class="cdc-header-mobile__title" role="heading">
<a href="/ebola/index.html">Ebola</a>
<button aria-label="Menu toggle" class="nav-link dropdown-toggle" data-bs-offset="0,20" id="mobileDropDownButton" type="button">
			Menu <i class="cdc-fa-angle-down"></i>
</button>
</div>
<div aria-labelledby="mobileDropDownButton" class="dropdown-menu cdc-mobile-menu">
<div class="cdc-mobile-menu-search">
<form action="https://search.cdc.gov/search/" aria-labelledby="cdc-mobile-search-toggle" class="cdc-mobile-search" id="cdc-mobile-search-body" method="GET" role="search">
<div class="input-group">
<input class="form-control cdc-mobile-search__input" data-search-input="" maxlength="300" name="query" placeholder="Search" required="" tabindex="-1" type="search"/>
<button class="btn btn-outline-secondary btn--clear" type="button"><span aria-hidden="true" class="cdc-fa-light cdc-fa-xmark"></span><span class="visually-hidden">clear</span></button>
<button class="btn btn-outline-secondary btn--search" type="submit"><i class="cdc-fa-light cdc-fa-magnifying-glass"></i><span class="visually-hidden">search</span></button>
</div>
</form>
</div>
<div class="cdc-mobile-menu-body">
<div aria-label="Audiences Navigation" class="cdc-mobile-audience accordion" role="navigation">
<div class="accordion-item" data-audience="gen">
<div class="accordion-header">
<button aria-controls="mobilemenu-gen" aria-expanded="false" class="accordion-button" data-bs-target="#mobilemenu-gen" data-bs-toggle="collapse" type="button">
<span class="accordion-button__text">
										For Everyone									</span>
</button>
</div>
<div class="accordion-collapse collapse" id="mobilemenu-gen">
<div class="accordion-body">
<ul>
<li class="truncate">
<a data-post-id="853" href="/ebola/situation-summary/index.html">
													Current Situation												</a>
</li>
<li class="truncate">
<a data-post-id="43" href="/ebola/about/index.html">
													About												</a>
</li>
<li class="truncate">
<a data-post-id="53" href="/ebola/signs-symptoms/index.html">
													Signs and Symptoms												</a>
</li>
<li class="truncate">
<a data-post-id="71" href="/ebola/outbreaks/index.html">
													Outbreak History												</a>
</li>
<li class="truncate">
<a data-post-id="54" href="/ebola/causes/index.html">
													How It Spreads												</a>
</li>
<li class="truncate">
<a data-post-id="854" href="/ebola/faq/index.html">
													FAQs												</a>
</li>
<li class="truncate">
<a data-post-id="76" href="/ebola/hcp/communication-resources/index.html">
													Ebola Communication Resources												</a>
</li>
<li>
<span class="item-link item-link--all">
<a href="/ebola/site.html#gen">
													View All												</a>
</span>
<span class="item-link item-link--home">
<a href="/ebola/index.html">
													Home												</a>
</span>
</li>
</ul>
</div>
</div>
</div>
<div class="accordion-item" data-audience="hcp">
<div class="accordion-header">
<button aria-controls="mobilemenu-hcp" aria-expanded="false" class="accordion-button" data-bs-target="#mobilemenu-hcp" data-bs-toggle="collapse" type="button">
<span class="accordion-button__text">
										Health Care Providers									</span>
</button>
</div>
<div class="accordion-collapse collapse" id="mobilemenu-hcp">
<div class="accordion-body">
<ul>
<li class="truncate">
<a data-post-id="73" href="/ebola/hcp/clinical-guidance/index.html">
													Clinical Guidance												</a>
</li>
<li class="truncate">
<a data-post-id="47" href="/ebola/hcp/clinical-signs/index.html">
													Clinical Features												</a>
</li>
<li class="truncate">
<a data-post-id="184" href="/ebola/hcp/vaccines/index.html">
													Vaccine Product Information												</a>
</li>
<li class="truncate">
<a data-post-id="75" href="/ebola/hcp/training/index.html">
													Training												</a>
</li>
<li>
<span class="item-link item-link--all">
<a href="/ebola/site.html#hcp">
													View All												</a>
</span>
<span class="item-link item-link--home">
<a href="/ebola/hcp/index.html">
													Home												</a>
</span>
</li>
</ul>
</div>
</div>
</div>
<div class="accordion-item" data-audience="php">
<div class="accordion-header">
<button aria-controls="mobilemenu-php" aria-expanded="false" class="accordion-button" data-bs-target="#mobilemenu-php" data-bs-toggle="collapse" type="button">
<span class="accordion-button__text">
										Public Health									</span>
</button>
</div>
<div class="accordion-collapse collapse" id="mobilemenu-php">
<div class="accordion-body">
<ul>
<li class="truncate">
<a data-post-id="878" href="/ebola/php/emergency-guidance/index.html">
													Interim Public Health Travel Guidance												</a>
</li>
<li class="truncate">
<a data-post-id="816" href="/ebola/php/public-health-strategy/index.html">
													Public Health Strategy												</a>
</li>
<li>
<span class="item-link item-link--all">
<a href="/ebola/site.html#php">
													View All												</a>
</span>
<span class="item-link item-link--home">
<a href="/ebola/php/index.html">
													Home												</a>
</span>
</li>
</ul>
</div>
</div>
</div>
<div class="accordion-item accordion-item__related">
<div aria-controls="mobilemenu-related" aria-expanded="false" class="accordion-header">
<button aria-controls="mobilemenu-related" aria-expanded="false" class="accordion-button" data-bs-target="#mobilemenu-related" data-bs-toggle="collapse" type="button">
<span class="accordion-button__text">
									Related Topics								</span>
</button>
</div>
<div class="accordion-collapse collapse" id="mobilemenu-related">
<div class="accordion-body">
<ul>
<li class="truncate">
<a data-post-id="" href="/viral-hemorrhagic-fevers/about/index.html">
											About Viral Hemorrhagic Fevers										</a>
</li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="cdc-mobile-menu-footer">
<a href="/ebola/index.html">
<span>Ebola</span>
</a>
</div>
</div>
<div aria-hidden="true" class="cdc-header-mobile__faux-title"> </div>
</div>
<div class="cdc-mobile-navbar">
<div class="cdc-mobile-navbar__paging">
</div>
<div class="cdc-mobile-navbar__links" tabindex="-1">
<a data-post-id="853" href="/ebola/situation-summary/index.html" tabindex="0">
				Current Situation			</a>
<a data-post-id="43" href="/ebola/about/index.html" tabindex="0">
				About			</a>
<a data-post-id="53" href="/ebola/signs-symptoms/index.html" tabindex="0">
				Signs and Symptoms			</a>
<a data-post-id="71" href="/ebola/outbreaks/index.html" tabindex="0">
				Outbreak History			</a>
<a data-post-id="54" href="/ebola/causes/index.html" tabindex="0">
				How It Spreads			</a>
<a data-post-id="854" href="/ebola/faq/index.html" tabindex="0">
				FAQs			</a>
<a data-post-id="76" href="/ebola/hcp/communication-resources/index.html" tabindex="0">
				Ebola Communication Resources			</a>
<a class="view-all dropdown-toggle" href="#">
					View Menu				</a>
</div>
</div>
</header>

In [6]:
headings = soup.find_all("h3")

headings

[<h3 class="cdc-callout__heading">Risk to the United States</h3>,
 <h3 id="heading-2uc2vo3t4q">Reported cases</h3>,
 <h3 id="heading-mm8nkmya-o">Map of affected areas</h3>,
 <h3 id="heading-wew3aijesq">For everyone</h3>,
 <h3 id="heading-5qsabxkvns">Travel information</h3>,
 <h3 id="heading-7fgo0jeya1">For healthcare providers</h3>,
 <h3 id="heading--swrmi3lio">For public health professionals</h3>,
 <h3 class="site-footer__links__header">
 <a class="cdc-footer__super-link" href="/ebola/index.html#gen">
 <span>For Everyone</span>
 <span class="cdc-icon cdc-fa-light cdc-fa-angle-right"></span>
 </a>
 </h3>,
 <h3 class="site-footer__links__header">
 <a class="cdc-footer__super-link" href="/ebola/hcp/index.html#hcp">
 <span>Health Care Providers</span>
 <span class="cdc-icon cdc-fa-light cdc-fa-angle-right"></span>
 </a>
 </h3>,
 <h3 class="site-footer__links__header">
 <a class="cdc-footer__super-link" href="/ebola/php/index.html#php">
 <span>Public Health</span>
 <span class="cdc-icon cdc-fa-light cdc-fa-angle-right"></span>
 </a>
 </h3>]

In [7]:
for heading in headings:
    print(heading.get_text(strip=True))

Risk to the United States
Reported cases
Map of affected areas
For everyone
Travel information
For healthcare providers
For public health professionals
For Everyone
Health Care Providers
Public Health

In [8]:
headings = soup.find_all("h3")

for heading in headings:
    if "Reported cases" in heading.get_text():
        print(heading)

<h3 id="heading-2uc2vo3t4q">Reported cases</h3>

In [9]:
reported_cases = None

for heading in headings:
    if "Reported cases" in heading.get_text():
        reported_cases = heading

reported_cases

In [10]:
reported_cases.find_next()

In [64]:
following = reported_cases.find_previous()
print(following.get_text(strip=True))

Latest data

In [12]:
reported_cases.find_next("div")

<div class="dfe-block dfe-block--cdcmodule cdc_visualization dfe-block--width-standard"><div class="dfe-block__inner"><div class="mb-3"><div class="wcms-viz-container" data-config-url="/ebola/situation-summary/modules/case-counts.json" data-host="www.cdc.gov" data-language="en" data-sid=""></div></div></div></div>

In [13]:
reported_cases.find_next("span")

In [14]:
div = reported_cases.find_next("div")
div.attrs

{'class': ['dfe-block',
  'dfe-block--cdcmodule',
  'cdc_visualization',
  'dfe-block--width-standard']}

In [15]:
div.get("data-config-url")

In [16]:
viz_div = soup.find("div", class_="wcms-viz-container")

viz_div

In [17]:
json_path = viz_div["data-config-url"]

print(json_path)

/ebola/situation-summary/modules/case-counts.json

In [18]:
base_url = "https://www.cdc.gov"

json_url = base_url + json_path

print(json_url)

https://www.cdc.gov/ebola/situation-summary/modules/case-counts.json

In [19]:
json_response = requests.get(json_url)

print(json_response.status_code)

200

In [20]:
print(json_response.text[:500])

{"dashboard":{"theme":"theme-blue","titleStyle":"small","sharedFilters":[]},"rows":[{"columns":[{"width":12,"widget":"table-p24zru0m"}]},{"columns":[{"width":12,"widget":"markup-include-rowok1zm"}],"uuid":"row-rxdtd4n1"}],"visualizations":{"table-p24zru0m":{"filters":[],"filterBehavior":"Filter Change","newViz":false,"openModal":true,"uid":"table-p24zru0m","type":"table","table":{"label":"Data Table","show":true,"showDownloadUrl":false,"showVertical":true,"expanded":true,"collapsible":false,"gro

In [21]:
case_data = json_response.json()

type(case_data)

case_data.keys()

dict_keys(['dashboard', 'rows', 'visualizations', 'table', 'errors', 'currentViewport', 'id', 'category', 'label', 'type', 'subType', 'orientation', 'icon', 'content', 'visualizationType', 'activeVizButtonID', 'version', 'migrations', 'general', 'locale', 'datasets'])

In [22]:
case_data["datasets"]

{'Ebola Case Counts': {'dataMetadata': {},
  'dataFileSize': 930,
  'dataFileName': '/wcms/vizdata/ebola/ebola-case-counts-web-updates.csv',
  'dataFileSourceType': 'url',
  'dataFileFormat': 'CSV',
  'preview': True,
  'dataUrl': '/wcms/vizdata/ebola/ebola-case-counts-web-updates.csv'}}

In [23]:
datasets = case_data["datasets"]

csv_path = datasets["Ebola Case Counts"]["dataUrl"]

print(csv_path)

/wcms/vizdata/ebola/ebola-case-counts-web-updates.csv

In [24]:
base_url = "https://www.cdc.gov"

csv_url = base_url + csv_path

print(csv_url)

https://www.cdc.gov/wcms/vizdata/ebola/ebola-case-counts-web-updates.csv

In [25]:
import sys

print(sys.executable)

c:\Users\User\Desktop\python_capstone_project\.venv\Scripts\python.exe

In [26]:
import pandas as pd

print(pd.__version__)

3.0.3

In [27]:
df = pd.read_csv(csv_url)

In [28]:
df.head()

,Location,Reported,Count,Footnote
0,"DRC (as of Jul 01, 2026)",Confirmed cases,1460,*Investigation of additional cases is ongoing ...
1,"DRC (as of Jul 01, 2026)",Confirmed deaths,452,NaN
2,"DRC (as of Jul 01, 2026)",Probable cases,0,NaN
3,"DRC (as of Jul 01, 2026)",Probable deaths,0,NaN
4,"Uganda (as of Jul 02, 2026)",Confirmed cases,20,NaN

Country

In [29]:
df["Country"] = df["Location"].str.extract(r"^(.*?)\s*\(", expand=False)

In [30]:
print(df[["Location", "Country"]].head())

                      Location Country
0     DRC (as of Jul 01, 2026)     DRC
1     DRC (as of Jul 01, 2026)     DRC
2     DRC (as of Jul 01, 2026)     DRC
3     DRC (as of Jul 01, 2026)     DRC
4  Uganda (as of Jul 02, 2026)  Uganda

Date

In [31]:
df["Update_Date"] = df["Location"].str.extract(
    r"\(as of (.*?)\)",
    expand=False
)

In [32]:
print(df[["Location", "Update_Date"]].head())

                      Location   Update_Date
0     DRC (as of Jul 01, 2026)  Jul 01, 2026
1     DRC (as of Jul 01, 2026)  Jul 01, 2026
2     DRC (as of Jul 01, 2026)  Jul 01, 2026
3     DRC (as of Jul 01, 2026)  Jul 01, 2026
4  Uganda (as of Jul 02, 2026)  Jul 02, 2026

In [33]:
df["Update_Date"] = pd.to_datetime(df["Update_Date"])

In [34]:
print(df[["Country", "Update_Date"]].head())

  Country Update_Date
0     DRC  2026-07-01
1     DRC  2026-07-01
2     DRC  2026-07-01
3     DRC  2026-07-01
4  Uganda  2026-07-02

In [35]:
country_df = df[["Country", "Update_Date", "Reported", "Count"]]

In [36]:
country_df

   Country Update_Date          Reported  Count
0      DRC  2026-07-01   Confirmed cases   1460
1      DRC  2026-07-01  Confirmed deaths    452
2      DRC  2026-07-01    Probable cases      0
3      DRC  2026-07-01   Probable deaths      0
4   Uganda  2026-07-02   Confirmed cases     20
5   Uganda  2026-07-02  Confirmed deaths      2
6   Uganda  2026-07-02    Probable cases      1
7   Uganda  2026-07-02   Probable deaths      1
8   France  2026-06-24   Confirmed cases      1
9   France  2026-06-24  Confirmed deaths      0
10  France  2026-06-24    Probable cases      0
11  France  2026-06-24   Probable deaths      0
12     NaN         NaT   Confirmed cases   1481
13     NaN         NaT  Confirmed deaths    454
14     NaN         NaT    Probable cases      1
15     NaN         NaT   Probable deaths      1

Remove totals

In [37]:
country_df = country_df.dropna(subset=["Country"])

In [38]:
country_df

   Country Update_Date          Reported  Count
0      DRC  2026-07-01   Confirmed cases   1460
1      DRC  2026-07-01  Confirmed deaths    452
2      DRC  2026-07-01    Probable cases      0
3      DRC  2026-07-01   Probable deaths      0
4   Uganda  2026-07-02   Confirmed cases     20
5   Uganda  2026-07-02  Confirmed deaths      2
6   Uganda  2026-07-02    Probable cases      1
7   Uganda  2026-07-02   Probable deaths      1
8   France  2026-06-24   Confirmed cases      1
9   France  2026-06-24  Confirmed deaths      0
10  France  2026-06-24    Probable cases      0
11  France  2026-06-24   Probable deaths      0

Storing in data base

In [39]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

countries table

In [40]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS countries (

    country_id INTEGER PRIMARY KEY AUTOINCREMENT,

    country_name TEXT NOT NULL UNIQUE

)
""")

report type table

In [41]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS report_types (

    report_type_id INTEGER PRIMARY KEY AUTOINCREMENT,

    report_name TEXT NOT NULL UNIQUE

)
""")

In [42]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS ebola_reports (

    report_id INTEGER PRIMARY KEY AUTOINCREMENT,

    country_id INTEGER NOT NULL,

    report_type_id INTEGER NOT NULL,

    update_date DATE NOT NULL,

    count INTEGER NOT NULL,

    FOREIGN KEY (country_id)
        REFERENCES countries(country_id),

    FOREIGN KEY (report_type_id)
        REFERENCES report_types(report_type_id)
)
""")

In [43]:
connection.commit()

In [44]:
countries = country_df["Country"].unique()
print(countries)

for country in countries:
    cursor.execute("""
        INSERT OR IGNORE INTO countries (country_name)
        VALUES (?)
    """, (country,))
    
connection.commit()

<ArrowStringArray>
['DRC', 'Uganda', 'France']
Length: 3, dtype: str

In [45]:
report_types = country_df["Reported"].unique()
print(report_types)

for report in report_types:
    cursor.execute("""
        INSERT OR IGNORE INTO report_types (report_name)
        VALUES (?)
    """, (report,))
    
connection.commit()

<ArrowStringArray>
['Confirmed cases', 'Confirmed deaths', 'Probable cases', 'Probable deaths']
Length: 4, dtype: str

In [46]:
for index, row in country_df.iterrows():
    country = row["Country"]
    report = row["Reported"]
    update_date = row["Update_Date"]
    count = row["Count"]

In [47]:
cursor.execute("""
SELECT country_id
FROM countries
WHERE country_name = ?
""", (country,))

country_id = cursor.fetchone()[0]

In [48]:
cursor.execute("""
SELECT report_type_id
FROM report_types
WHERE report_name = ?
""", (report,))

report_type_id = cursor.fetchone()[0]

In [49]:
update_date = update_date.strftime("%Y-%m-%d")

In [50]:
cursor.execute("""
INSERT INTO ebola_reports
(country_id, report_type_id, update_date, count)

VALUES (?, ?, ?, ?)
""", (
    country_id,
    report_type_id,
    update_date,
    count
))

In [51]:
connection.commit()

In [52]:
for index, row in country_df.iterrows():

    country = row["Country"]
    report = row["Reported"]
    update_date = row["Update_Date"]
    count = row["Count"]

    cursor.execute("""
    SELECT country_id
    FROM countries
    WHERE country_name = ?
    """, (country,))

    country_id = cursor.fetchone()[0]

    cursor.execute("""
    SELECT report_type_id
    FROM report_types
    WHERE report_name = ?
    """, (report,))

    report_type_id = cursor.fetchone()[0]

    update_date = update_date.strftime("%Y-%m-%d")

    cursor.execute("""
    INSERT INTO ebola_reports
    (country_id, report_type_id, update_date, count)

    VALUES (?, ?, ?, ?)
    """, (
        country_id,
        report_type_id,
        update_date,
        count
    ))

connection.commit()

In [53]:
cursor.execute("SELECT * FROM ebola_reports")

for row in cursor.fetchall():
    print(row)

(2, 1, 1, '2026-07-01', 1460)
(3, 1, 2, '2026-07-01', 452)
(4, 1, 3, '2026-07-01', 0)
(5, 1, 4, '2026-07-01', 0)
(6, 2, 1, '2026-07-02', 20)
(7, 2, 2, '2026-07-02', 2)
(8, 2, 3, '2026-07-02', 1)
(9, 2, 4, '2026-07-02', 1)
(10, 3, 1, '2026-06-24', 1)
(11, 3, 2, '2026-06-24', 0)
(12, 3, 3, '2026-06-24', 0)
(13, 3, 4, '2026-06-24', 0)
(14, 3, 4, '2026-06-24', 0)
(15, 1, 1, '2026-07-01', 1460)
(16, 1, 2, '2026-07-01', 452)
(17, 1, 3, '2026-07-01', 0)
(18, 1, 4, '2026-07-01', 0)
(19, 2, 1, '2026-07-02', 20)
(20, 2, 2, '2026-07-02', 2)
(21, 2, 3, '2026-07-02', 1)
(22, 2, 4, '2026-07-02', 1)
(23, 3, 1, '2026-06-24', 1)
(24, 3, 2, '2026-06-24', 0)
(25, 3, 3, '2026-06-24', 0)
(26, 3, 4, '2026-06-24', 0)
(27, 3, 4, '2026-06-24', 0)
(28, 1, 1, '2026-07-01', 1460)
(29, 1, 2, '2026-07-01', 452)
(30, 1, 3, '2026-07-01', 0)
(31, 1, 4, '2026-07-01', 0)
(32, 2, 1, '2026-07-02', 20)
(33, 2, 2, '2026-07-02', 2)
(34, 2, 3, '2026-07-02', 1)
(35, 2, 4, '2026-07-02', 1)
(36, 3, 1, '2026-06-24', 1)
(37, 3, 2, '2026-06-24', 0)
(38, 3, 3, '2026-06-24', 0)
(39, 3, 4, '2026-06-24', 0)

In [54]:
cursor.execute("""
DELETE FROM ebola_reports
WHERE report_id = 1
""")

connection.commit()

In [55]:
cursor.execute("""
SELECT
    c.country_name,
    r.report_name,
    e.update_date,
    e.count
FROM ebola_reports e
JOIN countries c
    ON e.country_id = c.country_id
JOIN report_types r
    ON e.report_type_id = r.report_type_id
ORDER BY c.country_name, r.report_type_id;
""")

for row in cursor.fetchall():
    print(row)

('DRC', 'Confirmed cases', '2026-07-01', 1460)
('DRC', 'Confirmed cases', '2026-07-01', 1460)
('DRC', 'Confirmed cases', '2026-07-01', 1460)
('DRC', 'Confirmed deaths', '2026-07-01', 452)
('DRC', 'Confirmed deaths', '2026-07-01', 452)
('DRC', 'Confirmed deaths', '2026-07-01', 452)
('DRC', 'Probable cases', '2026-07-01', 0)
('DRC', 'Probable cases', '2026-07-01', 0)
('DRC', 'Probable cases', '2026-07-01', 0)
('DRC', 'Probable deaths', '2026-07-01', 0)
('DRC', 'Probable deaths', '2026-07-01', 0)
('DRC', 'Probable deaths', '2026-07-01', 0)
('France', 'Confirmed cases', '2026-06-24', 1)
('France', 'Confirmed cases', '2026-06-24', 1)
('France', 'Confirmed cases', '2026-06-24', 1)
('France', 'Confirmed deaths', '2026-06-24', 0)
('France', 'Confirmed deaths', '2026-06-24', 0)
('France', 'Confirmed deaths', '2026-06-24', 0)
('France', 'Probable cases', '2026-06-24', 0)
('France', 'Probable cases', '2026-06-24', 0)
('France', 'Probable cases', '2026-06-24', 0)
('France', 'Probable deaths', '2026-06-24', 0)
('France', 'Probable deaths', '2026-06-24', 0)
('France', 'Probable deaths', '2026-06-24', 0)
('France', 'Probable deaths', '2026-06-24', 0)
('France', 'Probable deaths', '2026-06-24', 0)
('Uganda', 'Confirmed cases', '2026-07-02', 20)
('Uganda', 'Confirmed cases', '2026-07-02', 20)
('Uganda', 'Confirmed cases', '2026-07-02', 20)
('Uganda', 'Confirmed deaths', '2026-07-02', 2)
('Uganda', 'Confirmed deaths', '2026-07-02', 2)
('Uganda', 'Confirmed deaths', '2026-07-02', 2)
('Uganda', 'Probable cases', '2026-07-02', 1)
('Uganda', 'Probable cases', '2026-07-02', 1)
('Uganda', 'Probable cases', '2026-07-02', 1)
('Uganda', 'Probable deaths', '2026-07-02', 1)
('Uganda', 'Probable deaths', '2026-07-02', 1)
('Uganda', 'Probable deaths', '2026-07-02', 1)

In [56]:
cursor.execute("""
SELECT
    e.report_id,
    c.country_name,
    r.report_name,
    e.update_date,
    e.count

FROM ebola_reports e

JOIN countries c
ON e.country_id = c.country_id

JOIN report_types r
ON e.report_type_id = r.report_type_id

ORDER BY c.country_name, r.report_name;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

(2, 'DRC', 'Confirmed cases', '2026-07-01', 1460)
(15, 'DRC', 'Confirmed cases', '2026-07-01', 1460)
(28, 'DRC', 'Confirmed cases', '2026-07-01', 1460)
(3, 'DRC', 'Confirmed deaths', '2026-07-01', 452)
(16, 'DRC', 'Confirmed deaths', '2026-07-01', 452)
(29, 'DRC', 'Confirmed deaths', '2026-07-01', 452)
(4, 'DRC', 'Probable cases', '2026-07-01', 0)
(17, 'DRC', 'Probable cases', '2026-07-01', 0)
(30, 'DRC', 'Probable cases', '2026-07-01', 0)
(5, 'DRC', 'Probable deaths', '2026-07-01', 0)
(18, 'DRC', 'Probable deaths', '2026-07-01', 0)
(31, 'DRC', 'Probable deaths', '2026-07-01', 0)
(10, 'France', 'Confirmed cases', '2026-06-24', 1)
(23, 'France', 'Confirmed cases', '2026-06-24', 1)
(36, 'France', 'Confirmed cases', '2026-06-24', 1)
(11, 'France', 'Confirmed deaths', '2026-06-24', 0)
(24, 'France', 'Confirmed deaths', '2026-06-24', 0)
(37, 'France', 'Confirmed deaths', '2026-06-24', 0)
(12, 'France', 'Probable cases', '2026-06-24', 0)
(25, 'France', 'Probable cases', '2026-06-24', 0)
(38, 'France', 'Probable cases', '2026-06-24', 0)
(13, 'France', 'Probable deaths', '2026-06-24', 0)
(14, 'France', 'Probable deaths', '2026-06-24', 0)
(26, 'France', 'Probable deaths', '2026-06-24', 0)
(27, 'France', 'Probable deaths', '2026-06-24', 0)
(39, 'France', 'Probable deaths', '2026-06-24', 0)
(6, 'Uganda', 'Confirmed cases', '2026-07-02', 20)
(19, 'Uganda', 'Confirmed cases', '2026-07-02', 20)
(32, 'Uganda', 'Confirmed cases', '2026-07-02', 20)
(7, 'Uganda', 'Confirmed deaths', '2026-07-02', 2)
(20, 'Uganda', 'Confirmed deaths', '2026-07-02', 2)
(33, 'Uganda', 'Confirmed deaths', '2026-07-02', 2)
(8, 'Uganda', 'Probable cases', '2026-07-02', 1)
(21, 'Uganda', 'Probable cases', '2026-07-02', 1)
(34, 'Uganda', 'Probable cases', '2026-07-02', 1)
(9, 'Uganda', 'Probable deaths', '2026-07-02', 1)
(22, 'Uganda', 'Probable deaths', '2026-07-02', 1)
(35, 'Uganda', 'Probable deaths', '2026-07-02', 1)

In [57]:
cursor.execute("""
SELECT
    c.country_name,
    e.count

FROM ebola_reports e

JOIN countries c
ON e.country_id = c.country_id

JOIN report_types r
ON e.report_type_id = r.report_type_id

WHERE r.report_name = 'Confirmed cases'

ORDER BY e.count DESC;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

('DRC', 1460)
('DRC', 1460)
('DRC', 1460)
('Uganda', 20)
('Uganda', 20)
('Uganda', 20)
('France', 1)
('France', 1)
('France', 1)

In [58]:
cursor.execute("""
SELECT
    c.country_name,
    e.count

FROM ebola_reports e

JOIN countries c
ON e.country_id = c.country_id

JOIN report_types r
ON e.report_type_id = r.report_type_id

WHERE r.report_name = 'Confirmed cases'

ORDER BY e.count DESC;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

('DRC', 1460)
('DRC', 1460)
('DRC', 1460)
('Uganda', 20)
('Uganda', 20)
('Uganda', 20)
('France', 1)
('France', 1)
('France', 1)

In [59]:
cursor.execute("""
SELECT
    c.country_name,
    e.count

FROM ebola_reports e

JOIN countries c
ON e.country_id = c.country_id

JOIN report_types r
ON e.report_type_id = r.report_type_id

WHERE r.report_name = 'Probable cases'

ORDER BY e.count DESC;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

('Uganda', 1)
('Uganda', 1)
('Uganda', 1)
('DRC', 0)
('France', 0)
('DRC', 0)
('France', 0)
('DRC', 0)
('France', 0)

In [60]:
cursor.execute("""
SELECT
    c.country_name,
    COUNT(*) AS number_of_reports

FROM ebola_reports e

JOIN countries c
ON e.country_id = c.country_id

JOIN report_types r
ON e.report_type_id = r.report_type_id

WHERE r.report_name = 'Confirmed cases'

GROUP BY c.country_name;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

('DRC', 3)
('France', 3)
('Uganda', 3)

In [1]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS symptom_reports (

    report_id INTEGER PRIMARY KEY AUTOINCREMENT,

    person_name TEXT,

    country TEXT,

    symptoms TEXT,

    symptom_start_date TEXT,

    travel_history TEXT,

    contact_history TEXT,

    date_submitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS exposure_reports (

    exposure_id INTEGER PRIMARY KEY AUTOINCREMENT,

    person_name TEXT,

    country TEXT,

    exposure_type TEXT,

    exposure_date TEXT,

    comments TEXT,

    date_submitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS public_health_messages (

    message_id INTEGER PRIMARY KEY AUTOINCREMENT,

    name TEXT,

    email TEXT,

    country TEXT,

    subject TEXT,

    message TEXT,

    date_submitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)
""")

connection.commit()
connection.close()

print("Tables created successfully!")

Tables created successfully!

In [1]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

for table in cursor.fetchall():
    print(table)

connection.close()

('countries',)
('sqlite_sequence',)
('report_types',)
('ebola_reports',)
('symptom_reports',)
('exposure_reports',)
('public_health_messages',)

In [3]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS public_health_advice (

    advice_id INTEGER PRIMARY KEY AUTOINCREMENT,

    topic TEXT NOT NULL,

    advice TEXT NOT NULL,

    last_updated TEXT

)
""")

connection.commit()
connection.close()

print("Table created successfully.")

Table created successfully.

In [4]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

advice = [

(
"Prevention",
"Wash your hands regularly with soap and water. Avoid contact with blood or body fluids of infected individuals.",
"2026-07-08"
),

(
"Travel Advice",
"Before travelling, check the latest Ebola outbreak updates and follow guidance from public health authorities.",
"2026-07-08"
),

(
"Symptoms",
"If you develop fever, vomiting, diarrhea, weakness or unexplained bleeding after possible exposure, seek medical attention immediately.",
"2026-07-08"
),

(
"Vaccination",
"The Ervebo vaccine is recommended for eligible high-risk individuals in areas where Ebola outbreaks are occurring.",
"2026-07-08"
)

]

cursor.executemany("""

INSERT INTO public_health_advice
(topic, advice, last_updated)

VALUES (?, ?, ?)

""", advice)

connection.commit()
connection.close()

print("Advice inserted successfully.")

Advice inserted successfully.

In [5]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

cursor.execute("SELECT * FROM public_health_advice")

print(cursor.fetchall())

connection.close()

[(1, 'Prevention', 'Wash your hands regularly with soap and water. Avoid contact with blood or body fluids of infected individuals.', '2026-07-08'), (2, 'Travel Advice', 'Before travelling, check the latest Ebola outbreak updates and follow guidance from public health authorities.', '2026-07-08'), (3, 'Symptoms', 'If you develop fever, vomiting, diarrhea, weakness or unexplained bleeding after possible exposure, seek medical attention immediately.', '2026-07-08'), (4, 'Vaccination', 'The Ervebo vaccine is recommended for eligible high-risk individuals in areas where Ebola outbreaks are occurring.', '2026-07-08')]

In [6]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

cursor.execute("PRAGMA table_info(public_health_messages)")

for column in cursor.fetchall():
    print(column)

connection.close()

(0, 'message_id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 0, None, 0)
(2, 'email', 'TEXT', 0, None, 0)
(3, 'country', 'TEXT', 0, None, 0)
(4, 'subject', 'TEXT', 0, None, 0)
(5, 'message', 'TEXT', 0, None, 0)
(6, 'date_submitted', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)

In [7]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

try:
    cursor.execute("""
        ALTER TABLE public_health_messages
        ADD COLUMN status TEXT DEFAULT 'Pending'
    """)
    print("Status column added.")
except sqlite3.OperationalError as e:
    print(e)

try:
    cursor.execute("""
        ALTER TABLE public_health_messages
        ADD COLUMN response TEXT DEFAULT 'Awaiting response'
    """)
    print("Response column added.")
except sqlite3.OperationalError as e:
    print(e)

connection.commit()
connection.close()

Status column added.
Response column added.

In [8]:
import sqlite3

connection = sqlite3.connect("ebola_surveillance.db")
cursor = connection.cursor()

cursor.execute("PRAGMA table_info(public_health_messages)")

for column in cursor.fetchall():
    print(column)

connection.close()

(0, 'message_id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 0, None, 0)
(2, 'email', 'TEXT', 0, None, 0)
(3, 'country', 'TEXT', 0, None, 0)
(4, 'subject', 'TEXT', 0, None, 0)
(5, 'message', 'TEXT', 0, None, 0)
(6, 'date_submitted', 'TIMESTAMP', 0, 'CURRENT_TIMESTAMP', 0)
(7, 'status', 'TEXT', 0, "'Pending'", 0)
(8, 'response', 'TEXT', 0, "'Awaiting response'", 0)